concert/config/routes.rb
Concert::Application.routes.draw do
  resources :viewers

  get "welcome/index"

  root :to => "articles#index"  
    
  match "/auth/:provider/callback" => "sessions#create"  
       

  resources :usuarios

  resources :dtypes

  resources :utypes

  resources :users

  resources :bands

  resources :sites

  resources :name_concerts

  resources :usuario_sessions
  match 'login' => 'usuario_sessions#new', as: :login
  match 'logout' => 'usuario_sessions#destroy', as: :logout

  root :to => 'welcome#index'

end

concert/app/models/band.rb
class Band < ActiveRecord::Base
  attr_accessible :band_id, :member, :name, :style, :usuario_ids
  has_and_belongs_to_many :name_concert
  has_and_belongs_to_many :usuario

validates_presence_of :name, :message => '^ Debes ingresar un nombre de Banda'
#validates_presence_of :band_id, :message => '^ Debes elegir un miembro'


  has_many :band_usuarios
  has_many :usuarios, :through => :band_usuarios

  has_many :name_concerts

end

concert/app/models/district.rb
class District < ActiveRecord::Base
  attr_accessible :district, :id_district
end

concert/app/models/dtype.rb
class Dtype < ActiveRecord::Base
  attr_accessible :id, :tdd
  belongs_to :utype
end

concert/app/models/name_concert.rb
class NameConcert < ActiveRecord::Base
  attr_accessible :end_date, :name, :start_date, :site_id, :band_id, :usuario_id
  belongs_to :site
  belongs_to :band
  belongs_to :usuario
  has_many :goconcerts
end

concert/app/models/role.rb
class Role < ActiveRecord::Base
  attr_accessible :rol, :rol_id
  belongs_to :usuario
end

concert/app/models/site.rb
class Site < ActiveRecord::Base
  attr_accessible :address, :district, :name, :phone, :site_id, :latitude, :longitude
  #validates_presence_of :map
  validates :name, :address, :presence => true
  validates_uniqueness_of :name

  acts_as_gmappable :process_geocoding => false
  acts_as_gmappable :validation => true
  
  has_many :name_concerts

  def gmaps4rails_address
  	"#{self.address}, Lima, Peru"
  end	

  def gmaps4rails_infowindow
	      "<h1>#{name} </h1>"
  end



end

concert/app/models/type_user.rb
class TypeUser < ActiveRecord::Base
  attr_accessible :clave, :correo, :finicio, :nombre, :rol_defecto, :tur_id
end

concert/app/models/user_role.rb
class UserRole < ActiveRecord::Base
  attr_accessible :rol_id, :tur_id
end

concert/app/models/usuario.rb
class Usuario < ActiveRecord::Base
authenticates_with_sorcery!
 attr_accessible :password, :password_confirmation, :crypted_password, :email, :salt, :name, :apaterno, :amaterno,
   :email_confirmation, :utype_id, :gender, :dtype_id, :num_identity
  has_many :goconcerts
	has_one :utype
    has_and_belongs_to_many :band

validates :name, :presence => {:message => " no puede estar en blanco"}
validates :apaterno, :presence => true
validates :amaterno, :presence => true
validates_confirmation_of :email
validate :check_password
validates_uniqueness_of :email
validates_uniqueness_of :num_identity


has_many :band_usuarios
has_many :bands, :through => :band_usuarios

has_many :name_concerts

#validates :password, :presence => {:message => " No puede estar en blanco"},:confirmation => {:message => " No coinciden"}
#validates :email, :presence => {:message => " no puede estar en blanco"},:confirmation => {:message => "No coinciden"},:uniqueness => {:message => "Usuario ya existe"}

def check_password
    if self.new_record?
      errors.add(:base, "Password can't be blank") if self.password.blank?
      errors.add(:base, "Password and confirmation does not match") unless self.password == self.password_confirmation
      errors.add(:base, "Password must be at least 8 chars long") if self.password.to_s.size.to_i < 4
    else
      if self.password.blank?
        errors.add(:base, "Password can't be blank") if self.password.blank?
      else
        errors.add(:base, "Password and confirmation does not match") unless self.password == self.password_confirmation
        errors.add(:base, "Password must be at least 8 chars long") if self.password.to_s.size.to_i < 4
      end
    end
  end

 end

concert/app/models/utype.rb
class Utype < ActiveRecord::Base
  attr_accessible :id, :tdu
	belongs_to :user
	has_one :dtype

end

concert/app/models/viewer.rb
class Viewer < ActiveRecord::Base
  attr_accessible :concert_id, :integer, :integer, :user_id, :v_id
end

concert/app/controllers/name_concerts_controller.rb
class NameConcertsController < ApplicationController
  #def buscar
  #  #@name_concerts = NameConcert.all
  #  @name_concerts = NameConcert.find(:all, :conditions => ["name LIKE ?", "Mo%"])
  #  respond_to do |format|
  #    format.html # index.html.erb
  #    format.json { render json: @name_concerts }
  #  end
  #end

  # GET /name_concerts
  # GET /name_concerts.json
  def index
    @name_concerts = NameConcert.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @name_concerts }
    end
  end

  # GET /name_concerts/1
  # GET /name_concerts/1.json
  def show
    @name_concert = NameConcert.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @name_concert }
    end
  end

  # GET /name_concerts/new
  # GET /name_concerts/new.json
  def new
    @name_concert = NameConcert.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @name_concert }
    end
  end

  # GET /name_concerts/1/edit
  def edit
    @name_concert = NameConcert.find(params[:id])
  end

  # POST /name_concerts
  # POST /name_concerts.json
  def create
    @name_concert = NameConcert.new(params[:name_concert])

    respond_to do |format|
      if @name_concert.save
        format.html { redirect_to @name_concert, notice: 'Name concert was successfully created.' }
        format.json { render json: @name_concert, status: :created, location: @name_concert }
      else
        format.html { render action: "new" }
        format.json { render json: @name_concert.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /name_concerts/1
  # PUT /name_concerts/1.json
  def update
    @name_concert = NameConcert.find(params[:id])

    respond_to do |format|
      if @name_concert.update_attributes(params[:name_concert])
        format.html { redirect_to @name_concert, notice: 'Name concert was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @name_concert.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /name_concerts/1
  # DELETE /name_concerts/1.json
  def destroy
    @name_concert = NameConcert.find(params[:id])
    @name_concert.destroy

    respond_to do |format|
      format.html { redirect_to name_concerts_url }
      format.json { head :no_content }
    end
  end
end

concert/app/helpers/bands_helper.rb
module BandsHelper
end

concert/app/helpers/dtypes_helper.rb
module DtypesHelper
end

concert/app/helpers/name_concerts_helper.rb
module NameConcertsHelper
end

concert/app/helpers/roles_helper.rb
module RolesHelper
end

concert/app/helpers/sessions_helper.rb
module SessionsHelper
end

concert/app/helpers/sites_helper.rb
module SitesHelper
end

concert/app/helpers/users_helper.rb
module UsersHelper
end

concert/app/helpers/usuarios_helper.rb
module UsuariosHelper
end

concert/app/helpers/utypes_helper.rb
module UtypesHelper
end

concert/app/helpers/viewers_helper.rb
module ViewersHelper
end

concert/app/helpers/welcome_helper.rb
module WelcomeHelper
end

concert/app/views/name_concerts/_form.html.erb
<%= form_for(@name_concert) do |f| %>
  <% if @name_concert.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@name_concert.errors.count, "error") %> prohibited this name_concert from being saved:</h2>

      <ul>
      <% @name_concert.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Nombre %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :Fecha_de_inicio %><br />
    <%= f.datetime_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :Fecha_de_fin %><br />
    <%= f.datetime_select :end_date %>
  </div>
  
  <div class="field">
    <%= f.label :Local %><br />
    <%= f.collection_select :site_id, Site.all, :id, :name, :prompt => true %>
  </div>

  <div class="field">
    <%= f.label :Banda %><br />
    <%= f.collection_select :band_id, Band.all, :id, :name, :prompt => true %>
  </div>

  <div class="field">
    <%= f.label :Usuario %><br />
    <%= f.collection_select :usuario_id, Usuario.all, :id, :name, :prompt => true %>
  </div>
  
  <div class="actions">
    <%= f.submit :Grabar %>
  </div>
<% end %>

concert/app/views/name_concerts/edit.html.erb
<h1>Editar concierto</h1>

<%= render 'form' %>

<%= link_to 'Ver', @name_concert %> |
<%= link_to 'Atras', name_concerts_path %>

concert/app/views/name_concerts/index.html.erb
<h1>Listado de conciertos</h1>

<table>
  <tr>
    <th>Nombre</th>
    <th>Fecha de inicio</th>
    <th>Fecha de fin</th>
    <th>Local</th>
    <th>Banda</th>
    <th>Usuario</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @name_concerts.each do |name_concert| %>
  <tr>
    <td><%= name_concert.name %></td>
    <td><%= name_concert.start_date %></td>
    <td><%= name_concert.end_date %></td>
    <td><%= name_concert.site.name %></td>
    <td><%= name_concert.band.name %></td>
    <td><%= name_concert.usuario.name %></td>
    <td><%= link_to 'Ver', name_concert %></td>
    <td><%= link_to 'Editar', edit_name_concert_path(name_concert) %></td>
    <td><%= link_to 'Eliminar', name_concert, method: :delete, data: { confirm: 'Eliminar concierto?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Nuevo', new_name_concert_path %>

concert/app/views/name_concerts/new.html.erb
<h1>Nuevo concierto</h1>

<%= render 'form' %>

<%= link_to 'Atras', name_concerts_path %>

concert/app/views/name_concerts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nombre:</b>
  <%= @name_concert.name %>
</p>

<p>
  <b>Fecha de inicio:</b>
  <%= @name_concert.start_date %>
</p>

<p>
  <b>Fecha de fin:</b>
  <%= @name_concert.end_date %>
</p>

<p>
  <b>Local:</b>
  <%= @name_concert.site.name %>
</p>

<p>
  <b>Banda:</b>
  <%= @name_concert.band.name %>
</p>

<p>
  <b>Usuario:</b>
  <%= @name_concert.usuario.name %>
</p>


<%= link_to 'Editar', edit_name_concert_path(@name_concert) %> |
<%= link_to 'Atras', name_concerts_path %>