concert/config/routes.rb
Concert::Application.routes.draw do
  resources :viewers

  get "welcome/index"

  root :to => "articles#index"  
    
  match "/auth/:provider/callback" => "sessions#create"  
       

  resources :usuarios

  resources :dtypes

  resources :utypes

  resources :users

  resources :bands

  resources :sites

  resources :name_concerts

  resources :usuario_sessions
  match 'login' => 'usuario_sessions#new', as: :login
  match 'logout' => 'usuario_sessions#destroy', as: :logout

  root :to => 'welcome#index'

end

concert/app/models/band.rb
class Band < ActiveRecord::Base
  attr_accessible :band_id, :member, :name, :style, :usuario_ids
  has_and_belongs_to_many :name_concert
  has_and_belongs_to_many :usuario

validates_presence_of :name, :message => '^ Debes ingresar un nombre de Banda'
#validates_presence_of :band_id, :message => '^ Debes elegir un miembro'


  has_many :band_usuarios
  has_many :usuarios, :through => :band_usuarios

  has_many :name_concerts

end

concert/app/models/district.rb
class District < ActiveRecord::Base
  attr_accessible :district, :id_district
end

concert/app/models/dtype.rb
class Dtype < ActiveRecord::Base
  attr_accessible :id, :tdd
  belongs_to :utype
end

concert/app/models/name_concert.rb
class NameConcert < ActiveRecord::Base
  attr_accessible :end_date, :name, :start_date, :site_id, :band_id, :usuario_id
  belongs_to :site
  belongs_to :band
  belongs_to :usuario
  has_many :goconcerts
end

concert/app/models/role.rb
class Role < ActiveRecord::Base
  attr_accessible :rol, :rol_id
  belongs_to :usuario
end

concert/app/models/site.rb
class Site < ActiveRecord::Base
  attr_accessible :address, :district, :name, :phone, :site_id, :latitude, :longitude
  #validates_presence_of :map
  validates :name, :address, :presence => true
  validates_uniqueness_of :name

  acts_as_gmappable :process_geocoding => false
  acts_as_gmappable :validation => true
  
  has_many :name_concerts

  def gmaps4rails_address
  	"#{self.address}, Lima, Peru"
  end	

  def gmaps4rails_infowindow
	      "<h1>#{name} </h1>"
  end



end

concert/app/models/type_user.rb
class TypeUser < ActiveRecord::Base
  attr_accessible :clave, :correo, :finicio, :nombre, :rol_defecto, :tur_id
end

concert/app/models/user_role.rb
class UserRole < ActiveRecord::Base
  attr_accessible :rol_id, :tur_id
end

concert/app/models/usuario.rb
class Usuario < ActiveRecord::Base
authenticates_with_sorcery!
 attr_accessible :password, :password_confirmation, :crypted_password, :email, :salt, :name, :apaterno, :amaterno,
   :email_confirmation, :utype_id, :gender, :dtype_id, :num_identity
  has_many :goconcerts
	has_one :utype
    has_and_belongs_to_many :band

validates :name, :presence => {:message => " no puede estar en blanco"}
validates :apaterno, :presence => true
validates :amaterno, :presence => true
validates_confirmation_of :email
validate :check_password
validates_uniqueness_of :email
validates_uniqueness_of :num_identity


has_many :band_usuarios
has_many :bands, :through => :band_usuarios

has_many :name_concerts

#validates :password, :presence => {:message => " No puede estar en blanco"},:confirmation => {:message => " No coinciden"}
#validates :email, :presence => {:message => " no puede estar en blanco"},:confirmation => {:message => "No coinciden"},:uniqueness => {:message => "Usuario ya existe"}

def check_password
    if self.new_record?
      errors.add(:base, "Password can't be blank") if self.password.blank?
      errors.add(:base, "Password and confirmation does not match") unless self.password == self.password_confirmation
      errors.add(:base, "Password must be at least 8 chars long") if self.password.to_s.size.to_i < 4
    else
      if self.password.blank?
        errors.add(:base, "Password can't be blank") if self.password.blank?
      else
        errors.add(:base, "Password and confirmation does not match") unless self.password == self.password_confirmation
        errors.add(:base, "Password must be at least 8 chars long") if self.password.to_s.size.to_i < 4
      end
    end
  end

 end

concert/app/models/utype.rb
class Utype < ActiveRecord::Base
  attr_accessible :id, :tdu
	belongs_to :user
	has_one :dtype

end

concert/app/models/viewer.rb
class Viewer < ActiveRecord::Base
  attr_accessible :concert_id, :integer, :integer, :user_id, :v_id
end

concert/app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  # GET /usuarios
  # GET /usuarios.json
  def index
    @usuarios = Usuario.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @usuarios }
    end
  end


  # GET /usuarios/1
  # GET /usuarios/1.json
  def show
    @usuario = Usuario.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @usuario }
    end
  end

  # GET /usuarios/new
  # GET /usuarios/new.json
  def new
    @usuario = Usuario.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @usuario }
    end
  end

  


  # GET /usuarios/1/edit
  def edit
    @usuario = Usuario.find(params[:id])
  end

  # POST /usuarios
  # POST /usuarios.json
  def create
    @usuario = Usuario.new(params[:usuario])

    respond_to do |format|
      if @usuario.save
        format.html { redirect_to @usuario, notice: 'Usuario was successfully created.' }
        format.json { render json: @usuario, status: :created, location: @usuario }
      else
        format.html { render action: "new" }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /usuarios/1
  # PUT /usuarios/1.json
  def update
    @usuario = Usuario.find(params[:id])

    respond_to do |format|
      if @usuario.update_attributes(params[:usuario])
        format.html { redirect_to @usuario, notice: 'Usuario was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

def validates_password
    @usuario.new
    if form.render[:crypted_password] != form.render[:password_confirmation]
      App.alert("Su password no coincide, vuelvalo a intentar")
    end
 end

  # DELETE /usuarios/1
  # DELETE /usuarios/1.json
  def destroy
    @usuario = Usuario.find(params[:id])
    @usuario.destroy

    respond_to do |format|
      format.html { redirect_to usuarios_url }
      format.json { head :no_content }
    end
  end
end

concert/app/helpers/bands_helper.rb
module BandsHelper
end

concert/app/helpers/districts_helper.rb
module DistrictsHelper
end

concert/app/helpers/dtypes_helper.rb
module DtypesHelper
end

concert/app/helpers/roles_helper.rb
module RolesHelper
end

concert/app/helpers/sessions_helper.rb
module SessionsHelper
end

concert/app/helpers/sites_helper.rb
module SitesHelper
end

concert/app/helpers/users_helper.rb
module UsersHelper
end

concert/app/helpers/usuarios_helper.rb
module UsuariosHelper
end

concert/app/helpers/utypes_helper.rb
module UtypesHelper
end

concert/app/helpers/viewers_helper.rb
module ViewersHelper
end

concert/app/helpers/welcome_helper.rb
module WelcomeHelper
end

concert/app/views/usuarios/_form.html.erb
<%= form_for(@usuario) do |f| %>
  <% if @usuario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@usuario.errors.count, "error") %> prohibited this usuario from being saved:</h2>

      <ul>
      <% @usuario.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <div class="field">
    <%= f.label :Tipo_de_Usuarios %><br />
    <%= f.collection_select :utype_id, Utype.all, :id, :tdu, :prompt => true %>
  </div>

  <div class="field">
    <%= f.label :Nombre %><br />
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :Apellido_Paterno %><br />
    <%= f.text_field :apaterno %>
  </div>

  <div class="field">
    <%= f.label :Apellido_Materno %><br />
    <%= f.text_field :amaterno %>
  </div>


  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>

    <div class="field">
    <%= f.label :email_confirmation %><br />
    <%= f.text_field :email_confirmation %>
  </div>
  
  

  <div class="field">
    <% genders = {'Femenino' => 'F', 'Masculino' => 'M'} %>
       <%= f.label :Sexo %><br />
      <fieldset>
        <% lista = genders.sort  %>
        <% lista.each do |gender | %>
        <%= f.radio_button :gender, gender[1] %>
        <label for="<%= gender[1] %>"><%= gender[0] %></label>
     <% end %>
      </fieldset>
   </div>

 <div class="field">
    <%= f.label :Tipo_de_Documento %><br />
    <%= f.collection_select :dtype_id, Dtype.all, :id, :tdd, :prompt => true %>
  </div>
  
  <div class="field">
    <%= f.label :Nro_de_Documento %><br />
    <%= f.text_field :num_identity %>
  </div>
  
  <div class="field">
    <%= f.label :Ingrese_password %><br />
    <%= f.password_field :password %>
  </div>
 
  <div class="field">
    <%= f.label :Confirme_Paswword %><br />
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= f.submit :Crear_Usuario %>
  </div>
<% end %>

concert/app/views/usuarios/edit.html.erb
<h1>Editing usuario</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @usuario %> |
<%= link_to 'Volver', usuarios_path %>

concert/app/views/usuarios/index.html.erb
<h1>Lista de Usuarios</h1>

<table>
  <tr>
    <th>Email</th>
    <th>Password</th>
    <th>Salt</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @usuarios.each do |usuario| %>
  <tr>
    <td><%= usuario.email %></td>
  
   
    <td><%= link_to 'Mostrar', usuario %></td>
    <td><%= link_to 'Editar', edit_usuario_path(usuario) %></td>
    <td><%= link_to 'Destroy', usuario, method: :delete, data: { confirm: '¿Estas Seguro?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Nuevo Usuario', new_usuario_path %>

concert/app/views/usuarios/new.html.erb
<h1>Nuevo Usuario</h1>

<%= render 'form' %>

<%= link_to 'Volver', usuarios_path %>

concert/app/views/usuarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Mail:</b>
  <%= @usuario.name %>
</p>

<p>
  <b>Email:</b>
  <%= @usuario.email %>
</p>




<%= link_to 'Editar', edit_usuario_path(@usuario) %> |
<%= link_to 'Volver', usuarios_path %>