concert/config/routes.rb
Concert::Application.routes.draw do
  resources :viewers

  get "welcome/index"

  root :to => "articles#index"  
    
  match "/auth/:provider/callback" => "sessions#create"  
       

  resources :usuarios

  resources :dtypes

  resources :utypes

  resources :users

  resources :bands

  resources :sites

  resources :name_concerts

  resources :usuario_sessions
  match 'login' => 'usuario_sessions#new', as: :login
  match 'logout' => 'usuario_sessions#destroy', as: :logout

  root :to => 'welcome#index'

end

concert/app/models/band.rb
class Band < ActiveRecord::Base
  attr_accessible :band_id, :member, :name, :style, :usuario_ids
  has_and_belongs_to_many :name_concert
  has_and_belongs_to_many :usuario

validates_presence_of :name, :message => '^ Debes ingresar un nombre de Banda'
#validates_presence_of :band_id, :message => '^ Debes elegir un miembro'


  has_many :band_usuarios
  has_many :usuarios, :through => :band_usuarios

  has_many :name_concerts

end

concert/app/models/district.rb
class District < ActiveRecord::Base
  attr_accessible :district, :id_district
end

concert/app/models/dtype.rb
class Dtype < ActiveRecord::Base
  attr_accessible :id, :tdd
  belongs_to :utype
end

concert/app/models/name_concert.rb
class NameConcert < ActiveRecord::Base
  attr_accessible :end_date, :name, :start_date, :site_id, :band_id, :usuario_id
  belongs_to :site
  belongs_to :band
  belongs_to :usuario
  has_many :goconcerts
end

concert/app/models/role.rb
class Role < ActiveRecord::Base
  attr_accessible :rol, :rol_id
  belongs_to :usuario
end

concert/app/models/site.rb
class Site < ActiveRecord::Base
  attr_accessible :address, :district, :name, :phone, :site_id, :latitude, :longitude
  #validates_presence_of :map
  validates :name, :address, :presence => true
  validates_uniqueness_of :name

  acts_as_gmappable :process_geocoding => false
  acts_as_gmappable :validation => true
  
  has_many :name_concerts

  def gmaps4rails_address
  	"#{self.address}, Lima, Peru"
  end	

  def gmaps4rails_infowindow
	      "<h1>#{name} </h1>"
  end



end

concert/app/models/type_user.rb
class TypeUser < ActiveRecord::Base
  attr_accessible :clave, :correo, :finicio, :nombre, :rol_defecto, :tur_id
end

concert/app/models/user_role.rb
class UserRole < ActiveRecord::Base
  attr_accessible :rol_id, :tur_id
end

concert/app/models/usuario.rb
class Usuario < ActiveRecord::Base
authenticates_with_sorcery!
 attr_accessible :password, :password_confirmation, :crypted_password, :email, :salt, :name, :apaterno, :amaterno,
   :email_confirmation, :utype_id, :gender, :dtype_id, :num_identity
  has_many :goconcerts
	has_one :utype
    has_and_belongs_to_many :band

validates :name, :presence => {:message => " no puede estar en blanco"}
validates :apaterno, :presence => true
validates :amaterno, :presence => true
validates_confirmation_of :email
validate :check_password
validates_uniqueness_of :email
validates_uniqueness_of :num_identity


has_many :band_usuarios
has_many :bands, :through => :band_usuarios

has_many :name_concerts

#validates :password, :presence => {:message => " No puede estar en blanco"},:confirmation => {:message => " No coinciden"}
#validates :email, :presence => {:message => " no puede estar en blanco"},:confirmation => {:message => "No coinciden"},:uniqueness => {:message => "Usuario ya existe"}

def check_password
    if self.new_record?
      errors.add(:base, "Password can't be blank") if self.password.blank?
      errors.add(:base, "Password and confirmation does not match") unless self.password == self.password_confirmation
      errors.add(:base, "Password must be at least 8 chars long") if self.password.to_s.size.to_i < 4
    else
      if self.password.blank?
        errors.add(:base, "Password can't be blank") if self.password.blank?
      else
        errors.add(:base, "Password and confirmation does not match") unless self.password == self.password_confirmation
        errors.add(:base, "Password must be at least 8 chars long") if self.password.to_s.size.to_i < 4
      end
    end
  end

 end

concert/app/models/utype.rb
class Utype < ActiveRecord::Base
  attr_accessible :id, :tdu
	belongs_to :user
	has_one :dtype

end

concert/app/models/viewer.rb
class Viewer < ActiveRecord::Base
  attr_accessible :concert_id, :integer, :integer, :user_id, :v_id
end

concert/app/controllers/viewers_controller.rb
class ViewersController < ApplicationController
  # GET /viewers
  # GET /viewers.json
  def index
    @viewers = Viewer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @viewers }
    end
  end

  # GET /viewers/1
  # GET /viewers/1.json
  def show
    @viewer = Viewer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @viewer }
    end
  end

  # GET /viewers/new
  # GET /viewers/new.json
  def new
    @viewer = Viewer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @viewer }
    end
  end

  # GET /viewers/1/edit
  def edit
    @viewer = Viewer.find(params[:id])
  end

  # POST /viewers
  # POST /viewers.json
  def create
    @viewer = Viewer.new(params[:viewer])

    respond_to do |format|
      if @viewer.save
        format.html { redirect_to @viewer, notice: 'Viewer was successfully created.' }
        format.json { render json: @viewer, status: :created, location: @viewer }
      else
        format.html { render action: "new" }
        format.json { render json: @viewer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /viewers/1
  # PUT /viewers/1.json
  def update
    @viewer = Viewer.find(params[:id])

    respond_to do |format|
      if @viewer.update_attributes(params[:viewer])
        format.html { redirect_to @viewer, notice: 'Viewer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @viewer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /viewers/1
  # DELETE /viewers/1.json
  def destroy
    @viewer = Viewer.find(params[:id])
    @viewer.destroy

    respond_to do |format|
      format.html { redirect_to viewers_url }
      format.json { head :no_content }
    end
  end
end

concert/app/helpers/bands_helper.rb
module BandsHelper
end

concert/app/helpers/districts_helper.rb
module DistrictsHelper
end

concert/app/helpers/dtypes_helper.rb
module DtypesHelper
end

concert/app/helpers/roles_helper.rb
module RolesHelper
end

concert/app/helpers/sessions_helper.rb
module SessionsHelper
end

concert/app/helpers/sites_helper.rb
module SitesHelper
end

concert/app/helpers/users_helper.rb
module UsersHelper
end

concert/app/helpers/usuarios_helper.rb
module UsuariosHelper
end

concert/app/helpers/utypes_helper.rb
module UtypesHelper
end

concert/app/helpers/viewers_helper.rb
module ViewersHelper
end

concert/app/helpers/welcome_helper.rb
module WelcomeHelper
end

concert/app/views/viewers/_form.html.erb
<%= form_for(@viewer) do |f| %>
  <% if @viewer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@viewer.errors.count, "error") %> prohibited this viewer from being saved:</h2>

      <ul>
      <% @viewer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :v_id %><br />
    <%= f.number_field :v_id %>
  </div>
  <div class="field">
    <%= f.label :concert_id %><br />
    <%= f.text_field :concert_id %>
  </div>
  <div class="field">
    <%= f.label :integer %><br />
    <%= f.text_field :integer %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :integer %><br />
    <%= f.text_field :integer %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

concert/app/views/viewers/edit.html.erb
<h1>Editing viewer</h1>

<%= render 'form' %>

<%= link_to 'Show', @viewer %> |
<%= link_to 'Back', viewers_path %>

concert/app/views/viewers/index.html.erb
<h1>Listing viewers</h1>

<table>
  <tr>
    <th>V</th>
    <th>Concert</th>
    <th>Integer</th>
    <th>User</th>
    <th>Integer</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @viewers.each do |viewer| %>
  <tr>
    <td><%= viewer.v_id %></td>
    <td><%= viewer.concert_id %></td>
    <td><%= viewer.integer %></td>
    <td><%= viewer.user_id %></td>
    <td><%= viewer.integer %></td>
    <td><%= link_to 'Show', viewer %></td>
    <td><%= link_to 'Edit', edit_viewer_path(viewer) %></td>
    <td><%= link_to 'Destroy', viewer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Viewer', new_viewer_path %>

concert/app/views/viewers/new.html.erb
<h1>New viewer</h1>

<%= render 'form' %>

<%= link_to 'Back', viewers_path %>

concert/app/views/viewers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>V:</b>
  <%= @viewer.v_id %>
</p>

<p>
  <b>Concert:</b>
  <%= @viewer.concert_id %>
</p>

<p>
  <b>Integer:</b>
  <%= @viewer.integer %>
</p>

<p>
  <b>User:</b>
  <%= @viewer.user_id %>
</p>

<p>
  <b>Integer:</b>
  <%= @viewer.integer %>
</p>


<%= link_to 'Edit', edit_viewer_path(@viewer) %> |
<%= link_to 'Back', viewers_path %>